name: Mirror to GitLab

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history, all refs)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git push --mirror "https://oauth2:${GITLAB_TOKEN}@gitlab.com/mihkelpeets65/serverless-shortener.git"
